const Colors = {
  light: {
    background: "#FFFFFF",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    popover: "#FFFFFF",
    popoverForeground: "#0A0A0A",
    primary: "#5841C7",
    primaryForeground: "#FFFFFF",
    secondary: "#FFFFFF",
    secondaryForeground: "#1A1A1A",
    muted: "#F5F5F5",
    mutedForeground: "#737373",
    accent: "#F5F5F5",
    accentForeground: "#0A0A0A",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5E5",
    input: "#E5E5E5",
    ring: "#A3A3A3",
    text: "#0A0A0A",
    textSecondary: "#737373",
    surface: "#FAFAFA",
    success: "#4ADE80",
    error: "#DC2626",
    warning: "#F59E0B",
    sidebar: "#FAFAFA",
    sidebarForeground: "#0A0A0A",
    sidebarPrimary: "#1A1A1A",
    sidebarPrimaryForeground: "#FAFAFA",
    sidebarAccent: "#F5F5F5",
    sidebarAccentForeground: "#1A1A1A",
    sidebarBorder: "#E5E5E5",
    sidebarRing: "#A3A3A3",
  },
  dark: {
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#000000",
    cardForeground: "#FAFAFA",
    popover: "#FFFFFF",
    popoverForeground: "#0A0A0A",
    primary: "#7C3AED",
    primaryForeground: "#F3E8FF",
    secondary: "#7C3AED",
    secondaryForeground: "#F5F5F5",
    muted: "#FFFFFF",
    mutedForeground: "#F9F9F9",
    accent: "#FFFFFF",
    accentForeground: "#0A0A0A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5E5",
    input: "#E5E5E5",
    ring: "#A3A3A3",
    text: "#FFFFFF",
    textSecondary: "#A3A3A3",
    surface: "#1A1A1A",
    success: "#4ADE80",
    error: "#EF4444",
    warning: "#F59E0B",
    sidebar: "#FAFAFA",
    sidebarForeground: "#0A0A0A",
    sidebarPrimary: "#1A1A1A",
    sidebarPrimaryForeground: "#FAFAFA",
    sidebarAccent: "#F5F5F5",
    sidebarAccentForeground: "#1A1A1A",
    sidebarBorder: "#E5E5E5",
    sidebarRing: "#737373",
  },
  primary: "#5841C7",
  secondary: "#7C3AED",
  accent: "#5841C7",
  background: "#FFFFFF",
  surface: "#FAFAFA",
  surfaceVariant: "#F5F5F5",
  text: "#0A0A0A",
  textSecondary: "#737373",
  success: "#4ADE80",
  error: "#DC2626",
  warning: "#F59E0B",
  cardBackground: "#FFFFFF",
  border: "#E5E5E5",
  gradientStart: "#5841C7",
  gradientEnd: "#7C3AED",
  gradientTop: "#FFFFFF",
  gradientBottom: "#F5F5F5",
  radius: 10,
  shadow: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  shadowMd: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  shadowLg: {
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
}

export default Colors;
